[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.mbstring']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan octane:frankenphp --host=0.0.0.0 --port=${PORT:-8000}'